### ISSUE TITLE
Translate README for `Loyalsoldier/geoip`

### ISSUE THREAD

**Issue by markpash** [noql-net/org#1]
Translate the README for [Loyalsoldier/geoip](https://github.com/Loyalsoldier/geoip) to English and submit a PR to upstream repo to create `README_en.md`.

**Comment by 3aaber** [comment]
I made the [PR](https://github.com/Loyalsoldier/geoip/pull/86/files)

**Comment by markpash** [comment]
@3aaber Thank you :) .
The owner of that project closed your PR. So I forked it into the noql-net org, and have committed your changes. Hopefully the owner can reconsider, but if not, then we will maintain the fork.

**Comment by 3aaber** [comment]
Ok thanks mark. so I go to the next task in list
