### ISSUE TITLE
Research Fdroid or alternative method for android package delivery

### ISSUE THREAD

**Issue by markpash** [noql-net/org#14]
There are a number of android apps that either don't exist on the play store, or don't exist on fdroid.
Let's have a custom fdroid repository, which will contain a full list of anti-censorship apps. For example apps like v2rayNG.
This custom repository should initially contain a selection of apps that are fetched from the compiled releases from the github release page for each project. This should be automated (using GitHub actions) as much as possible.

**Comment by yuki-tsubaki** [comment]
Where is this being done? It would be nice to have a bit more to go off of to know that the apps in the F-Droid repo are safe, unmodified versions of the apps taken directly from the releases.

Of course I love the work that you're doing, but with such a high stakes thing as censorship circumvention for people living under authoritarian regimes, a bit extra transparency would be welcome in my opinion.

Of course, for technical android users (who still want simple updates) using something like Obtainium is an option. I think the F-Droid repo is a good way to reach more people more easily (it gets rid of barriers), but I also want to be more sure of it's security before recommending it to people.
